name: Pull Request Test && Merge
on: [pull_request]
jobs:

  install:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm-256color
      COLORTERM: truecolor
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ run bash rsi.sh --yes"
      - name: run RSI install
        run: |
          bash rsi.sh --yes
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: All good - tagging for automerge
        if: ${{ success() }}
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.comment.body, '/add-labels') }}
        with:
          labels: bug
